### ISSUE TITLE
What the fuck?

### ISSUE THREAD

**Issue by unityblows** [StringVar/.emacs.d#4]
It appears your emacs configuration blows.

Executing the git clone command provided in the readme seems to fail:

![image](https://user-images.githubusercontent.com/52715589/60995376-a172c100-a30f-11e9-8d76-e1bcb1640a49.png)

And cloning the repo directly and having emacs compile the configuration results in countless compiler warnings:

![image](https://user-images.githubusercontent.com/52715589/60995710-50170180-a310-11e9-8e23-dba9769a65a3.png)

**Comment by StringVar** [comment]
`git clone --recurse-submodules git@github.com:StringVar/.emacs.d.git`
the url `git@github.com:StringVar/.emacs.d.git` uses ssh, I always set up a ssh key with github for every computer I'm on. That error is because you don't have a key or you have not setup ssh with github.

`git clone --recurse-submodules https://github.com/StringVar/.emacs.d.git` is just the same. there is just a separate snippets folder as a submodule. --recurse-submodules just populates it. But it really doesn't matter.

As for the warnings use-package byte compiles the packages files which spits out those warnings. They don't stick around after launching emacs again. I have no control over other packages code. There are now 62 packages, a few free variables that don't do anything is fine.

This is just my personal configuration, not a distribution(yet). I would just pick and choose these configurations depending on what you need rather than forking the entire project.
[space_station.org contains all configuration in one giant organized org file](https://github.com/StringVar/.emacs.d/blob/master/space_station.org). Root around there.

Also don't swear in titles.

**Comment by unityblows** [comment]
Oh, I was under the impression swearing on github was encouraged:

![image](https://user-images.githubusercontent.com/52715589/61253727-39f9ae80-a71f-11e9-9242-b136bc50a100.png)

![image](https://user-images.githubusercontent.com/52715589/61253739-48e06100-a71f-11e9-8f9c-f5a5ff734335.png)

![image](https://user-images.githubusercontent.com/52715589/61253760-5f86b800-a71f-11e9-93f2-b8fdcf5ac8fb.png)

(  ͡°  ͜ʖ  ͡°)
