### ISSUE TITLE
Profanity on GitHub

### ISSUE THREAD

**Issue by unityblows** [StringVar/.emacs.d#6]
Please don't curse on GitHub.

![image](https://user-images.githubusercontent.com/52715589/61488979-ccd85a00-a966-11e9-884d-0cc84946054c.png)

![image](https://user-images.githubusercontent.com/52715589/61488987-d235a480-a966-11e9-8fe5-20b2049d6685.png)

![image](https://user-images.githubusercontent.com/52715589/61488997-d792ef00-a966-11e9-97e0-84c831899e7c.png)

**Comment by StringVar** [comment]
Look at how unhelpful those commits I made were.

When Tackling issues on github a title explaining what the issue is almost as important as how to solve it.

I would prefer to have titles and commit messages reflecting the work put into them. You have the wrong idea about how much I care about cursing. 

I was (and still) am an offender of good commit messages and issue tracking. But I still want to do better.
